version: '3'
services:
  mongo:
    image: mongo
    container_name: airbnb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
    - 27019:27017
    volumes:
    - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5